/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexao.*;
import java.awt.BorderLayout;
import java.awt.Image;
import java.net.URL;
import java.sql.SQLException;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Contato;
import modelo.Funcionario;
import modelo.Motorista;
import modelo.TabelaSet;
import modelo.Veiculo;

/**
 *
 * @author 20162bsi0325
 */
public class Home1 extends javax.swing.JFrame {
    boolean flag = true;
    int checkClick = 0;
    /**
     * Creates new form Home
     */
    public Home1() {
        initComponents();
        this.setLocationRelativeTo(null);
        setContentPane(Home); 
        Date dataHoraAtual = new Date();
        String data1 = new SimpleDateFormat("dd/MM/yyyy").format(dataHoraAtual);
        String hora1 = new SimpleDateFormat("EEEE, HH:mm zzzz").format(dataHoraAtual);
        data.setText(data1);
        hora.setText(hora1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        Home = new javax.swing.JPanel();
        Label_Home = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Servico = new javax.swing.JPanel();
        Label_Servico = new javax.swing.JLabel();
        botaoCadastrarServico = new javax.swing.JButton();
        buscarServico = new javax.swing.JTextField();
        botaoBuscarServico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaServico = new javax.swing.JTable();
        listarServico = new javax.swing.JButton();
        Veiculos = new javax.swing.JPanel();
        Label_Veiculo = new javax.swing.JLabel();
        pesquisarVeiculos = new javax.swing.JTextField();
        botaoPesquisarVeiculos = new javax.swing.JButton();
        botaoCadastrarVeiculos = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaVeiculos = new javax.swing.JTable();
        salario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        listarVeiculos = new javax.swing.JButton();
        Funcionarios = new javax.swing.JPanel();
        Label_Funcionarios = new javax.swing.JLabel();
        pesquisarFuncionarios = new javax.swing.JTextField();
        botaoPesquisarFuncionarios = new javax.swing.JButton();
        botaoCadastrarFuncionario = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaFuncionarios = new javax.swing.JTable();
        Label_Principal3 = new javax.swing.JLabel();
        pesquisarMotorista = new javax.swing.JTextField();
        botaopesquisarMotorista = new javax.swing.JButton();
        botaoCadastroMotorista = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaMotorista = new javax.swing.JTable();
        listarFuncionarios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Clientes = new javax.swing.JPanel();
        Label_Clientes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        pesquisarCliente = new javax.swing.JTextField();
        botaoPesquisarCliente = new javax.swing.JButton();
        botaoCadastrarCliente = new javax.swing.JButton();
        listarClientes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        servicosMenu = new javax.swing.JMenu();
        veiculosMenu = new javax.swing.JMenu();
        funcionariosMenu = new javax.swing.JMenu();
        clientesMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Home.setBackground(new java.awt.Color(255, 255, 255));

        Label_Home.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Home.setText("Inicio");

        data.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        data.setText("data");

        hora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hora.setText("hora");

        jLabel1.setText("Versão 1.1");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(554, Short.MAX_VALUE)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(data)
                    .addComponent(jLabel1)
                    .addComponent(hora))
                .addGap(121, 121, 121))
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Label_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(Label_Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hora)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(44, 44, 44))
        );

        Servico.setBackground(new java.awt.Color(255, 255, 255));

        Label_Servico.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Servico.setText("Serviço");

        botaoCadastrarServico.setText("Cadastrar Novo Serviço");
        botaoCadastrarServico.setBackground(new java.awt.Color(255, 255, 255));
        botaoCadastrarServico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        botaoCadastrarServico.setBorderPainted(false);
        botaoCadastrarServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarServicoMouseClicked(evt);
            }
        });
        botaoCadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarServicoActionPerformed(evt);
            }
        });

        buscarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarServicoActionPerformed(evt);
            }
        });

        botaoBuscarServico.setBackground(new java.awt.Color(255, 255, 255));
        botaoBuscarServico.setText("Buscar Serviço");
        botaoBuscarServico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botaoBuscarServico.setBorderPainted(false);
        botaoBuscarServico.setMaximumSize(new java.awt.Dimension(147, 23));
        botaoBuscarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarServicoActionPerformed(evt);
            }
        });

        tabelaServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "n°", "Veiculos", "Origem", "Destino", "Data Inicio", "Data Fim", "Cliente", "Status", "Detalhes"
            }
        ));
        jScrollPane1.setViewportView(tabelaServico);
        if (tabelaServico.getColumnModel().getColumnCount() > 0) {
            tabelaServico.getColumnModel().getColumn(6).setHeaderValue("Cliente");
            tabelaServico.getColumnModel().getColumn(7).setHeaderValue("Status");
            tabelaServico.getColumnModel().getColumn(8).setHeaderValue("Detalhes");
        }

        listarServico.setText("Listar");
        listarServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarServicoMouseClicked(evt);
            }
        });
        listarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ServicoLayout = new javax.swing.GroupLayout(Servico);
        Servico.setLayout(ServicoLayout);
        ServicoLayout.setHorizontalGroup(
            ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicoLayout.createSequentialGroup()
                .addGroup(ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ServicoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ServicoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Label_Servico)
                        .addGap(18, 18, 18)
                        .addComponent(buscarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoBuscarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(botaoCadastrarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(listarServico)
                .addGap(88, 88, 88))
        );
        ServicoLayout.setVerticalGroup(
            ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Servico)
                    .addComponent(buscarServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(listarServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        Veiculos.setBackground(new java.awt.Color(255, 255, 255));

        Label_Veiculo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Veiculo.setText("Veiculos");

        pesquisarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarVeiculosActionPerformed(evt);
            }
        });

        botaoPesquisarVeiculos.setText("Pesquisar");

        botaoCadastrarVeiculos.setText("Cadastrar");
        botaoCadastrarVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarVeiculosMouseClicked(evt);
            }
        });
        botaoCadastrarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarVeiculosActionPerformed(evt);
            }
        });

        tabelaVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "n°", "Marca", "Modelo", "Ano", "RENAVAM", "Placa", "Cor", "Motorista", "Status", "Detalhes"
            }
        ));
        tabelaVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVeiculosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelaVeiculos);

        salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Salario");

        listarVeiculos.setText("Listar");
        listarVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarVeiculosMouseClicked(evt);
            }
        });
        listarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarVeiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VeiculosLayout = new javax.swing.GroupLayout(Veiculos);
        Veiculos.setLayout(VeiculosLayout);
        VeiculosLayout.setHorizontalGroup(
            VeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VeiculosLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VeiculosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Label_Veiculo)
                .addGap(101, 101, 101)
                .addComponent(pesquisarVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoPesquisarVeiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VeiculosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(listarVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoCadastrarVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(VeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(VeiculosLayout.createSequentialGroup()
                    .addGap(253, 253, 253)
                    .addComponent(jLabel6)
                    .addGap(18, 18, 18)
                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(254, Short.MAX_VALUE)))
        );
        VeiculosLayout.setVerticalGroup(
            VeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VeiculosLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(VeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Veiculo)
                    .addComponent(pesquisarVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisarVeiculos)
                    .addComponent(botaoCadastrarVeiculos))
                .addGap(13, 13, 13)
                .addComponent(listarVeiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(VeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(VeiculosLayout.createSequentialGroup()
                    .addGap(250, 250, 250)
                    .addGroup(VeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addContainerGap(250, Short.MAX_VALUE)))
        );

        Funcionarios.setBackground(new java.awt.Color(255, 255, 255));

        Label_Funcionarios.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Funcionarios.setText("Funcionarios");

        pesquisarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarFuncionariosActionPerformed(evt);
            }
        });

        botaoPesquisarFuncionarios.setText("Pesquisar");

        botaoCadastrarFuncionario.setText("Cadastrar");
        botaoCadastrarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarFuncionarioMouseClicked(evt);
            }
        });
        botaoCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarFuncionarioActionPerformed(evt);
            }
        });

        tabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "n°", "Nome", "Endereço", "CPF", "Email", "Detalhes"
            }
        ));
        tabelaFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaFuncionarios);

        Label_Principal3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Principal3.setText("Motorista");

        pesquisarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarMotoristaActionPerformed(evt);
            }
        });

        botaopesquisarMotorista.setText("Pesquisar");

        botaoCadastroMotorista.setText("Cadastrar");
        botaoCadastroMotorista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastroMotoristaMouseClicked(evt);
            }
        });
        botaoCadastroMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroMotoristaActionPerformed(evt);
            }
        });

        tabelaMotorista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "n°", "Nome", "Endereço", "CPF", "Email", "CNH", "Categoria", "Validade", "Detalhes"
            }
        ));
        tabelaMotorista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMotoristaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelaMotorista);

        listarFuncionarios.setText("Listar");
        listarFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarFuncionariosMouseClicked(evt);
            }
        });
        listarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarFuncionariosActionPerformed(evt);
            }
        });

        jLabel3.setText("Clique no codigo da linha que deseja excluir ou alterar");

        javax.swing.GroupLayout FuncionariosLayout = new javax.swing.GroupLayout(Funcionarios);
        Funcionarios.setLayout(FuncionariosLayout);
        FuncionariosLayout.setHorizontalGroup(
            FuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FuncionariosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Label_Principal3)
                .addGap(99, 99, 99)
                .addComponent(pesquisarMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaopesquisarMotorista)
                .addGap(53, 53, 53)
                .addComponent(botaoCadastroMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(FuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FuncionariosLayout.createSequentialGroup()
                .addGroup(FuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FuncionariosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Label_Funcionarios)
                        .addGap(74, 74, 74)
                        .addComponent(pesquisarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoPesquisarFuncionarios))
                    .addGroup(FuncionariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(FuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FuncionariosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(listarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoCadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        FuncionariosLayout.setVerticalGroup(
            FuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FuncionariosLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(FuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Funcionarios, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pesquisarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoPesquisarFuncionarios)
                        .addComponent(botaoCadastrarFuncionario)))
                .addGap(14, 14, 14)
                .addGroup(FuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listarFuncionarios)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(FuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaopesquisarMotorista)
                    .addComponent(botaoCadastroMotorista)
                    .addComponent(Label_Principal3))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        Clientes.setBackground(new java.awt.Color(255, 255, 255));

        Label_Clientes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Clientes.setText("Cliente");

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "n°", "Nome", "CPF", "CNPJ", "Contato", "Endereço", "Título 7", "Título 8"
            }
        ));
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaClientes);

        pesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarClienteActionPerformed(evt);
            }
        });

        botaoPesquisarCliente.setText("Pesquisar");

        botaoCadastrarCliente.setText("Cadastrar");
        botaoCadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarClienteMouseClicked(evt);
            }
        });
        botaoCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarClienteActionPerformed(evt);
            }
        });

        listarClientes.setText("Listar");
        listarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarClientesMouseClicked(evt);
            }
        });

        jLabel2.setText("Clique no codigo da linha que deseja excluir ou alterar");

        javax.swing.GroupLayout ClientesLayout = new javax.swing.GroupLayout(Clientes);
        Clientes.setLayout(ClientesLayout);
        ClientesLayout.setHorizontalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(ClientesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ClientesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClientesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ClientesLayout.createSequentialGroup()
                        .addComponent(Label_Clientes)
                        .addGap(101, 101, 101)
                        .addComponent(pesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoPesquisarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(botaoCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        ClientesLayout.setVerticalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientesLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Clientes)
                    .addComponent(pesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisarCliente)
                    .addComponent(botaoCadastrarCliente))
                .addGap(18, 18, 18)
                .addComponent(listarClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        homeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/home.png"))); // NOI18N
        homeMenu.setText("Home");
        homeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(homeMenu);

        servicosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/support.png"))); // NOI18N
        servicosMenu.setText("Serviços");
        servicosMenu.setIconTextGap(2);
        servicosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servicosMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(servicosMenu);

        veiculosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/truck.png"))); // NOI18N
        veiculosMenu.setText("Veiculos");
        veiculosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                veiculosMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(veiculosMenu);

        funcionariosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/employee.png"))); // NOI18N
        funcionariosMenu.setText("Funcionarios");
        funcionariosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funcionariosMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(funcionariosMenu);

        clientesMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/avatar.png"))); // NOI18N
        clientesMenu.setText("Clientes");
        clientesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(clientesMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Servico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Veiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Funcionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Servico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Veiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Funcionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void servicosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicosMenuMouseClicked
        setContentPane(Servico); 
       
    }//GEN-LAST:event_servicosMenuMouseClicked

    private void homeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenuMouseClicked
        setContentPane(Home);
    }//GEN-LAST:event_homeMenuMouseClicked

    private void botaoCadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarServicoActionPerformed

    private void buscarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarServicoActionPerformed

    private void pesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarClienteActionPerformed

    private void botaoCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarClienteActionPerformed

    private void pesquisarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarFuncionariosActionPerformed

    private void botaoCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarFuncionarioActionPerformed

    private void pesquisarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarMotoristaActionPerformed

    private void botaoCadastroMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastroMotoristaActionPerformed

    private void pesquisarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarVeiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarVeiculosActionPerformed

    private void botaoCadastrarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarVeiculosActionPerformed
                  // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarVeiculosActionPerformed

    private void veiculosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veiculosMenuMouseClicked
        // TODO add your handling code here:
        setContentPane(Veiculos);   
        Veiculos.setLayout(new BorderLayout());

    }//GEN-LAST:event_veiculosMenuMouseClicked

    private void funcionariosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariosMenuMouseClicked
        // TODO add your handling code here:
         
        setContentPane(Funcionarios); 
        Funcionarios.setLayout(new BorderLayout());
   
    }//GEN-LAST:event_funcionariosMenuMouseClicked

    private void clientesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMenuMouseClicked
        // TODO add your handling code here:
        setContentPane(Clientes);  
        Clientes.setLayout(new BorderLayout());
  
    }//GEN-LAST:event_clientesMenuMouseClicked

    private void botaoCadastrarServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarServicoMouseClicked
        // TODO add your handling code here:
        CadastroServico cadastro_Servico = new CadastroServico();
        cadastro_Servico.setVisible(true);
        
    }//GEN-LAST:event_botaoCadastrarServicoMouseClicked

    private void botaoCadastrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarClienteMouseClicked
        // TODO add your handling code here:
        CadastroCliente Cadastro_Cliente = new CadastroCliente();
        
        Cadastro_Cliente.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarClienteMouseClicked

    private void botaoCadastrarVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarVeiculosMouseClicked
        // TODO add your handling code here:
        CadastroVeiculo Cadastro_Veiculo = new CadastroVeiculo();
        Cadastro_Veiculo.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarVeiculosMouseClicked

    private void botaoCadastrarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarFuncionarioMouseClicked
        // TODO add your handling code here:
        CadastroFuncionario Cadastro_Funcionario = new CadastroFuncionario();
        Cadastro_Funcionario.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarFuncionarioMouseClicked

    private void botaoBuscarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoBuscarServicoActionPerformed

    private void botaoCadastroMotoristaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastroMotoristaMouseClicked
        CadastroMotorista Cadatro_Motorista = new CadastroMotorista();
        Cadatro_Motorista.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastroMotoristaMouseClicked

    private void listarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarServicoActionPerformed

    private void salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioActionPerformed

    private void listarVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarVeiculosMouseClicked
        // TODO add your handling code here:
        VeiculoBD veiculoBD = new VeiculoBD();
        ArrayList veiculos = null;
        try {
            veiculos = veiculoBD.select("");
        } catch (SQLException ex) {
            Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
        }

        TabelaSet aux = new TabelaSet();
        aux.setDadosTabelaVeiculos(veiculos,tabelaVeiculos); 
    }//GEN-LAST:event_listarVeiculosMouseClicked

    private void listarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarVeiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarVeiculosActionPerformed

    private void listarFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarFuncionariosMouseClicked
        // TODO add your handling code here:
        FuncionarioBD funcionarioBD = new FuncionarioBD();
        ArrayList funcionarios = null;
        try {
            funcionarios = funcionarioBD.select("");
        } catch (SQLException ex) {
            Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        TabelaSet aux = new TabelaSet();
        aux.setDadosTabelaFuncionario(funcionarios,tabelaFuncionarios); 
//        
        MotoristaBD motoristaBD = new MotoristaBD();
        ArrayList motoristas = null;
        try {
            motoristas = motoristaBD.select("");
        } catch (SQLException ex) {
            Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
        }
        TabelaSet aux2 = new TabelaSet();
        aux2.setDadosTabelaMotorista(motoristas,tabelaMotorista); 
        
    }//GEN-LAST:event_listarFuncionariosMouseClicked

    private void listarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarFuncionariosActionPerformed

    private void listarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarClientesMouseClicked
        // TODO add your handling code here:
        ClienteBD clienteBD = new ClienteBD();
        ArrayList clientes = null;
        try {
            clientes = clienteBD.select("");
        } catch (SQLException ex) {
            Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.err.println(clientes);
        TabelaSet aux = new TabelaSet();
        aux.setDadosTabelaCliente(clientes,tabelaClientes);
    }//GEN-LAST:event_listarClientesMouseClicked

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        // TODO add your handling code here:
        String linhaSelecionada = "";
        String colunaSelecionada = "";
        ArrayList clientes = null;
        if(tabelaClientes.getSelectedRow() > -1 ){
            int linha = tabelaClientes.getSelectedRow();
            int coluna = tabelaClientes.getSelectedColumn();
            DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
            linhaSelecionada = modelo.getValueAt(linha, 0).toString();
            colunaSelecionada = modelo.getValueAt(coluna, 0).toString();
            if (coluna == 0){
                int op = Integer.parseInt(JOptionPane.showInputDialog("Digite qual opção desejada:  \n 1-Deletar: \n 2-Alterar:"));
                System.err.println(op);
                if (op == 1) {
                    //Deletar 
                    ClienteBD clienteBD = new ClienteBD();
                    int codigo = Integer.parseInt (tabelaClientes.getValueAt(linha, 0).toString());
                    System.err.println(codigo);
                    try {
                        clienteBD.delet(codigo);
                    } catch (SQLException ex) {
                        Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                                    //Alterar
                    ClienteBD clienteBD = new ClienteBD();
                    int codigo =  Integer.parseInt(tabelaClientes.getValueAt(linha, 0).toString());
                    System.err.println(codigo);
                    
                    try {
                        clientes = clienteBD.select("WHERE (id = "+codigo+")");
                    } catch (SQLException ex) {
                        Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    Cliente c = (Cliente) clientes.get(0);
                    System.err.println(c);
                    AlteracaoCliente frame = new AlteracaoCliente(c);
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                    
                    
                }
            }
        }
    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void tabelaFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFuncionariosMouseClicked
        // TODO add your handling code here:
                // TODO add your handling code here:
        ArrayList funcionarios = null;
        String linhaSelecionada = "";
        String colunaSelecionada = "";
        if(tabelaFuncionarios.getSelectedRow() > -1 ){
            int linha = tabelaFuncionarios.getSelectedRow();
            int coluna = tabelaFuncionarios.getSelectedColumn();
            System.err.println(coluna);
            DefaultTableModel modelo = (DefaultTableModel) tabelaFuncionarios.getModel();
            linhaSelecionada = modelo.getValueAt(linha, 0).toString();
            colunaSelecionada = modelo.getValueAt(coluna, 0).toString();
            if (coluna == 0){
                int op = Integer.parseInt(JOptionPane.showInputDialog("Digite qual opção desejada:  \n 1-Deletar: \n 2-Alterar:"));
                System.err.println(op);
                if (op == 1) {
                    //Deletar        
                    
                    FuncionarioBD funcionarioBD = new FuncionarioBD();
                    
                    int codigo = Integer.parseInt (tabelaFuncionarios.getValueAt(linha, 0).toString());
                    System.err.println(codigo);
                    try {
                        funcionarioBD.delet(codigo);
                    } catch (SQLException ex) {
                        Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    //Alterar
                    FuncionarioBD funcionarioBD = new FuncionarioBD();
                    int codigo =  Integer.parseInt(tabelaFuncionarios.getValueAt(linha, 0).toString());
                    System.err.println(codigo);
                    
                    try {
                        funcionarios = funcionarioBD.select("WHERE (id = "+codigo+")");
                    } catch (SQLException ex) {
                        Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    Funcionario f = (Funcionario) funcionarios.get(0);
                    System.err.println(f);
                    AlteracaoFuncionario frame = new AlteracaoFuncionario(f);
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                    
                }
            }
        }
    }//GEN-LAST:event_tabelaFuncionariosMouseClicked

    private void tabelaMotoristaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMotoristaMouseClicked
        // TODO add your handling code here:
                // TODO add your handling code here:
        ArrayList motorista = null;
        if(tabelaMotorista.getSelectedRow() > -1 ){
            int linha = tabelaMotorista.getSelectedRow();
            int coluna = tabelaMotorista.getSelectedColumn();
            if (coluna == 0){
                int op = Integer.parseInt(JOptionPane.showInputDialog("Digite qual opção desejada:  \n 1-Deletar: \n 2-Alterar:"));
                System.err.println(op);
                if (op == 1) {
                    //Deletar 
                    MotoristaBD motoristaBD = new MotoristaBD();
                    int codigo = Integer.parseInt (tabelaMotorista.getValueAt(linha, 4).toString());
                    System.err.println(codigo);
                    try {
                        motoristaBD.delet(codigo);
                    } catch (SQLException ex) {
                        Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    //Alterar
                                        //Alterar
                    MotoristaBD motoristaBD = new MotoristaBD();
                    int codigo =  Integer.parseInt(tabelaMotorista.getValueAt(linha, 0).toString());
                    System.err.println(codigo);

                    try {
                        motorista = motoristaBD.select("WHERE (id = "+codigo+")");
                    } catch (SQLException ex) {
                        Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    Motorista m = (Motorista) motorista.get(0);
                    System.err.println(m);
                    AlteracaoMotorista frame = new AlteracaoMotorista(m);
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                    
                }
            }
        }
    }//GEN-LAST:event_tabelaMotoristaMouseClicked

    private void listarServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarServicoMouseClicked
        // TODO add your handling code here:
         
        ServicoBD servicoBD = new ServicoBD();
        ArrayList servicos = null;
        try {
            servicos = servicoBD.select("");
        } catch (SQLException ex) {
            Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
        }
        Servico.setLayout(new BorderLayout());
        TabelaSet aux = new TabelaSet();
        aux.setDadosTabelaServico(servicos,tabelaServico); 
        // TODO add your handling code here:
    }//GEN-LAST:event_listarServicoMouseClicked

    private void tabelaVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVeiculosMouseClicked
        // TODO add your handling code here:
        String linhaSelecionada = "";
        String colunaSelecionada = "";
        ArrayList veiculo = null;
        if(tabelaVeiculos.getSelectedRow() > -1 ){
            int linha = tabelaVeiculos.getSelectedRow();
            int coluna = tabelaVeiculos.getSelectedColumn();
            System.err.println(coluna);
            DefaultTableModel modelo = (DefaultTableModel) tabelaVeiculos.getModel();
            linhaSelecionada = modelo.getValueAt(linha, 0).toString();
            colunaSelecionada = modelo.getValueAt(coluna, 0).toString();
            if (coluna == 0){
                int op = Integer.parseInt(JOptionPane.showInputDialog("Digite qual opção desejada:  \n 1-Deletar: \n 2-Alterar:"));
                System.err.println(op);
                if (op == 1) {
                    //Deletar        
                    
                    VeiculoBD veiculoBD = new VeiculoBD();
                    
                    int codigo = Integer.parseInt (tabelaVeiculos.getValueAt(linha, 0).toString());
                    System.err.println(codigo);
                    try {
                        veiculoBD.delet(codigo);
                    } catch (SQLException ex) {
                        Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else 
                if (op == 2){
                    //Alterar
                    VeiculoBD veiculoBD = new VeiculoBD();
                    String codigo =  (tabelaVeiculos.getValueAt(linha, 3).toString());
                    System.err.println(codigo);

                    try {
                        veiculo = veiculoBD.select("WHERE (placa = '"+codigo+"')");
                    } catch (SQLException ex) {
                        Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    Veiculo v = (Veiculo) veiculo.get(0);
                    System.err.println(v);
                    AlteracaoVeiculo frame = new AlteracaoVeiculo(v);
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                    
                }
            }
        }
    }//GEN-LAST:event_tabelaVeiculosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home1().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel Funcionarios;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel Label_Clientes;
    private javax.swing.JLabel Label_Funcionarios;
    private javax.swing.JLabel Label_Home;
    private javax.swing.JLabel Label_Principal3;
    private javax.swing.JLabel Label_Servico;
    private javax.swing.JLabel Label_Veiculo;
    private javax.swing.JPanel Servico;
    private javax.swing.JPanel Veiculos;
    private javax.swing.JButton botaoBuscarServico;
    private javax.swing.JButton botaoCadastrarCliente;
    private javax.swing.JButton botaoCadastrarFuncionario;
    private javax.swing.JButton botaoCadastrarServico;
    private javax.swing.JButton botaoCadastrarVeiculos;
    private javax.swing.JButton botaoCadastroMotorista;
    private javax.swing.JButton botaoPesquisarCliente;
    private javax.swing.JButton botaoPesquisarFuncionarios;
    private javax.swing.JButton botaoPesquisarVeiculos;
    private javax.swing.JButton botaopesquisarMotorista;
    private javax.swing.JTextField buscarServico;
    private javax.swing.JMenu clientesMenu;
    private javax.swing.JLabel data;
    private javax.swing.JMenu funcionariosMenu;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton listarClientes;
    private javax.swing.JButton listarFuncionarios;
    private javax.swing.JButton listarServico;
    private javax.swing.JButton listarVeiculos;
    private javax.swing.JTextField pesquisarCliente;
    private javax.swing.JTextField pesquisarFuncionarios;
    private javax.swing.JTextField pesquisarMotorista;
    private javax.swing.JTextField pesquisarVeiculos;
    private javax.swing.JTextField salario;
    private javax.swing.JMenu servicosMenu;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTable tabelaFuncionarios;
    private javax.swing.JTable tabelaMotorista;
    private javax.swing.JTable tabelaServico;
    private javax.swing.JTable tabelaVeiculos;
    private javax.swing.JMenu veiculosMenu;
    // End of variables declaration//GEN-END:variables

}
